реализовать основной сервис
IlmiraYagudina/java-explore-with-me pull request #2
Opened 2024-04-24 20:20 UTC by GutImozih73

2024-05-07 18:30 UTC, kriwsha requested changes

2024-05-07 18:30 UTC, kriwsha commented on main-service/src/main/java/ru/practicum/categories/service/CategoryService.java
> +            throw new SQLConstraintViolationException("Category with name = " + newCategoryDto.getName() + " already exists.");
Я бы рекомендовал дополнительно к вашему сообщению пробрасывать или логировать техническое сообщение из DataIntegrityViolationException. В этом случае при анализе проблем будет больше информации об ошибках.

2024-05-07 18:30 UTC, kriwsha commented on main-service/src/main/java/ru/practicum/compilations/service/CompilationService.java
> +            return compilations.stream().map(compilationMapper::compilationToCompilationDto).collect(Collectors.toList());
Лучше разбивать стрим на несколько строк для лучшей читаемости

2024-05-07 18:30 UTC, kriwsha commented on main-service/src/main/java/ru/practicum/compilations/service/CompilationService.java
> +            return compilations.stream().map(compilationMapper::compilationToCompilationDto).collect(Collectors.toList());
Здесь тоже бы забить на строки

2024-05-07 18:30 UTC, kriwsha commented on main-service/src/main/java/ru/practicum/events/dto/EventRequestStatusUpdateResult.java
> +    List<ParticipationRequestDto> confirmedRequests;
Не забывайте про модификаторы доступа

2024-05-07 18:30 UTC, kriwsha commented on main-service/src/main/java/ru/practicum/events/service/EventService.java
> +        Pageable pageable = sort.equals(EventSort.VIEWS)
Вообще, в конвенциях по написанию кода рекомендуют сравнивать перечисления через двойное равно

2024-05-07 18:30 UTC, kriwsha commented on main-service/src/main/java/ru/practicum/requests/service/RequestService.java
> +                throw new RequestConflictException("Only requests with status 'Pending' can be accepted or rejected.");
Это, конечно, дело вкуса, но я большой нелюбитель такой вложенности. Я бы на этом месте сделал стрим, в котором по операции anyMatch() получал boolean и решал выкидывать исключение. Иными словами, от одного уровня вложенности я бы избавился за счет стрима.

2024-05-07 20:52 UTC, GutImozih73 commented on main-service/src/main/java/ru/practicum/events/service/EventService.java
> +        Pageable pageable = sort.equals(EventSort.VIEWS)
Как я поняла, что для сравнения объектов в Java используется .equals(). Enum это объект. Решила использовать .equals() для сравнения, чтобы не нарушать единообразие сравнения объектов.

На мой взгляд, правильнее использовать .equals(), для меня он и наглядным, кажется, главное не забывать о правиле "Сравнение константы слева"

2024-05-07 20:56 UTC, GutImozih73 commented on main-service/src/main/java/ru/practicum/requests/service/RequestService.java
> +                throw new RequestConflictException("Only requests with status 'Pending' can be accepted or rejected.");
Я решила придерживаться единообразия стиля в проекте для читаемости, в связи с вышесказанным - использовать .equals

2024-05-08 13:20 UTC, kriwsha approved these changes

2024-05-08 13:53 UTC, merged